### ISSUE TITLE
com.badlogic.gdx.utils.GdxRuntimeException: File not found: main.atlas

### ISSUE THREAD

**Issue by ahollenbach** [ChainGangChase/cgc-game#19]
**System Info**
OSX 10.11.4
java 1.8.0_40 (not latest, but should be good enough?)

**Steps to Replicate**

``` bash
$ ./gradlew updateTextures
Configuration on demand is an incubating feature.
:updateTextures UP-TO-DATE

BUILD SUCCESSFUL

Total time: 2.314 secs

$ ./gradlew desktop:run
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
2016-06-03 20:38:52.931 java[33039:7103900] 20:38:52.931 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Controllers: added manager for application, 1 managers active
CONTROLLER: There are 0 controllers!
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: File not found: main.atlas (Internal)
    at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:103)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216)
    at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:211)
    at com.percipient24.cgc.ChaseApp.preLoad(ChaseApp.java:263)
    at com.percipient24.cgc.ChaseApp.create(ChaseApp.java:205)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
> Building 87% > :desktop:run^C
```

The project builds, I go to select from the main screen, and start game, and the screen goes black and the error pops up.

Note: Everything just built from scratch (although second time running, so all up to date)

**Comment by Percipient24** [comment]
Thanks for giving it a try! Sorry it didn't work out - but this will make it better for next time!

Try running `./gradlew npm_install` directly ... I'm new at this gradle thing.

The desired effect is for it to create a node_modules directory, and then a `./gradlew updateTextures` should copy files from there into android/assets.

**Comment by ahollenbach** [comment]
Thanks for the flair 😜 

Now I'm getting `File not found: data/cgcfont.fnt`. Can't seem to find it in any of the repos.

**Comment by Percipient24** [comment]
Oh. Yep. I'm going to put it in with cgc-i18n (since character sets and languages will likely go together). Will comment here once that's ready...

**Comment by Percipient24** [comment]
That should take care of data/cgcfont.fnt (and related .fnt issues). I also anticipated a data/maps.json that you didn't encounter yet (and hopefully won't).

You'll need to run another `./gradlew npm_install` to grab the latest cgc-i18n and get the .fnt files.

**Comment by ahollenbach** [comment]
Sweet! Success. It's launching but gets to the main screen and won't respond to my controller, and it might be missing audio? May have something to do with these errors?

```
$ ./gradlew desktop:run
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:run
2016-06-04 10:46:17.999 java[35735:7330397] 10:46:17.998 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Controllers: added manager for application, 1 managers active
CONTROLLER: There are 0 controllers!
FileHandler: File wom.txt not found. May not exist
FileHandler: File favorites.bin not found. May not exist
FileHandler: File preferences.bin not found. May not exist
AL lib: (EE) alc_cleanup: 1 device not closed

BUILD SUCCESSFUL

Total time: 54.24 secs
```

**Comment by Percipient24** [comment]
There's not much in the way of audio yet, and yeah, it looks like I need to update the audio API.

It's known to work with OUYA, PS3, and Xbox 360 controllers. I'll open another issue for supporting more.

For now, the keyboard should work (even if your controller doesn't).

Right side: Enter to select, Backspace to back out. ; joins/leaves character select. Arrow keys move. Quote punches. Enter jumps (while moving).

Left side: 1 to select. Tab to back out. Q joins/leaves character select. wasd moves. Tab punches. 1 jumps (while moving).

P pauses while in-game.

**Comment by Percipient24** [comment]
(I'm calling this one closed, since it's building - and we'll address the keyboard and audio in separate issues.)
